"""added join table for Post and Location models

Revision ID: 1305c4a71982
Revises: 2fd55547234b
Create Date: 2023-08-21 20:42:47.480531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1305c4a71982'
down_revision = '2fd55547234b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_location_association',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], name=op.f('fk_post_location_association_location_id_locations')),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_location_association_post_id_posts'))
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('image')

    op.drop_table('post_location_association')
    # ### end Alembic commands ###
