"""deleted an image attribute

Revision ID: 216100bbcded
Revises: 67a674b923aa
Create Date: 2023-08-21 22:20:05.907017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216100bbcded'
down_revision = '67a674b923aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
