"""deleted flag attribute

Revision ID: 4ad347fdd5e1
Revises: 3e3896f9e80e
Create Date: 2023-08-27 00:54:54.102812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ad347fdd5e1'
down_revision = '3e3896f9e80e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('flag')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flag', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
