"""deleted city attribute

Revision ID: 724b4bf35bb5
Revises: d9a6656d5caf
Create Date: 2023-08-22 23:13:18.225080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '724b4bf35bb5'
down_revision = 'd9a6656d5caf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('city')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
