"""added city

Revision ID: 835161fb9824
Revises: 724b4bf35bb5
Create Date: 2023-08-22 23:50:44.037799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '835161fb9824'
down_revision = '724b4bf35bb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_column('city')

    # ### end Alembic commands ###
